Feature/phase02
Star-Academy/Summer1403-SE-Team01 pull request #2
Opened 2024-07-22 14:54 UTC by AmirRezaZahedi

please check it

2024-07-23 06:50 UTC, tahadavari requested changes
check all

2024-07-23 06:50 UTC, tahadavari commented on InvertedIndex/Controller/DocHandler.cs
> +    public FileReader fr{get; set;}
نام گذاری دست

2024-07-23 06:50 UTC, tahadavari commented on InvertedIndex/Controller/FileReader.cs
> +    public async Task<string> Read(string path)
اسم تابع async داشته باشه

2024-07-23 06:50 UTC, tahadavari commented on InvertedIndex/Controller/SearchHandler.cs
> +            Query query = new Query(input);
var

2024-07-23 06:50 UTC, tahadavari commented on InvertedIndex/Controller/SearchHandler.cs
> +            Search search = new Search(query);
var

2024-07-23 06:50 UTC, tahadavari commented on InvertedIndex/Program.cs
> +        FileReader fr = new FileReader();
اینا همش var بشه

2024-07-23 06:50 UTC, tahadavari commented on InvertedIndex/Program.cs
> +        string folderPath = @"./EnglishData";
هارد کد نشه

2024-07-23 06:50 UTC, tahadavari commented on InvertedIndex/abstraction/IDataReader.cs
> +    public Task<string> Read(string path);
ReadAsync

2024-07-23 08:58 UTC, AmirRezaZahedi commented on InvertedIndex/Controller/DocHandler.cs
> +    public FileReader fr{get; set;}
where?

2024-07-23 13:01 UTC, tahadavari requested changes

2024-07-23 13:01 UTC, tahadavari commented on InvertedIndex/Controller/DocumentHandler.cs
>          this.fr = fr;
نام گذاری ها خوانا باشه 
fr
fe

2024-07-23 13:01 UTC, tahadavari commented on InvertedIndex/Controller/DocumentHandler.cs
> -public class DocHandler
reformat کنید کل فایل هارو

2024-07-23 13:01 UTC, tahadavari commented on InvertedIndex/Program.cs
> +        catch (Exception e)
Exception FolderNotfound 
کچ بشه ن هر اکسپشنی

2024-07-23 13:01 UTC, tahadavari commented on InvertedIndex/Controller/DocumentHandler.cs
>      public FileEditor fe{get; set;}
name convention C# هم بخونید ببینید درست نامگذاری کردید

2024-07-23 13:01 UTC, tahadavari commented on InvertedIndex/Controller/SearchHandler.cs
> +    public List<Document> getUniversal() {
پرایوت نمیتونه باشه ؟

2024-07-23 13:01 UTC, tahadavari commented on InvertedIndex/Controller/SearchHandler.cs
> +    public List<Document> ExtractOrdinaryResult(Query query)
این تابع می‌تونه تمیز تر و احتمالا به چنتا تابع تبدیل بشه یه فکری روش بکنید

2024-07-24 07:08 UTC, AliSK81 commented on project/IReadData.cs
چرا کدهای فاز 1 رو توی این pr حذف کردین؟

2024-07-24 07:08 UTC, AliSK81 commented on InvertedIndex/Program.cs
> +        var map = mapper.Map();
لیست داکیومنت رو اگر ورودی تابع بدیم بجای کانستراکتو مزیتی ایجاد میکنه؟

2024-07-24 07:08 UTC, AliSK81 commented on InvertedIndex/Controller/SearchHandler.cs
> +            resultHandler.Prepare(result, true);
بدون if else میشه نوشت

2024-07-24 07:08 UTC, AliSK81 commented on project/IReadData.cs
چرا فایل های فاز 1 توی این PR حذف شده؟

2024-07-24 07:10 UTC, AmirRezaZahedi commented on project/IReadData.cs
مگه نیازی هست به کد های فاز یک؟اونا **مرج شدن** فکر کنم

2024-07-24 07:10 UTC, AmirRezaZahedi commented on project/IReadData.cs
مگه نیازی هست به کد های فاز یک؟اونا **مرج شدن** فکر کنم

2024-07-24 07:39 UTC, hanaNrvtn commented on InvertedIndex/Program.cs
> +        var map = mapper.Map();
اگه ورودی بگیریم فکنم بهتره چون واسه دیکشنری های مختلف دیگه نیاز نیست کلاس جدید زد یا از نو پروپرتی دیکشنری رو ست کرد.

2024-07-24 13:45 UTC, merged