We start phase04 for pracrice unit test
Star-Academy/Summer1403-SE-Team01 pull request #4
Opened 2024-07-31 15:19 UTC by hanaNrvtn

2024-08-01 08:29 UTC, tahadavari requested changes

2024-08-01 08:29 UTC, tahadavari commented on phase04/FullTextSearch.Test/DocumentTest/DocumentBuilderTest.cs
> +            _documentBuilder = new DocumentBuilder(_documentFormatter);
_sut

2024-08-01 08:29 UTC, tahadavari commented on phase04/FullTextSearch.Test/DocumentTest/DocumentBuilderTest.cs
> +{
چرا when ندارن هیچ کدوم 
FunctionName_Should_When

2024-08-01 08:29 UTC, tahadavari commented on phase04/FullTextSearch.Test/MapTest/InvertedIndexMapperTest.cs
> +            var mapper = new InvertedIndexMapper();
_sut مگه نساختید ؟

2024-08-01 08:29 UTC, tahadavari commented on phase04/FullTextSearch.Test/QueryTest/QueryFormatter.cs
> +        [InlineData(new[] { "+ali", "+mohammad" }, new[] { "+ali", "-reza", "zahra", "+mohammad" }, '+')]
اینو با MemberData فک کنم زیبا تر بشه نوشت

2024-08-01 08:29 UTC, tahadavari commented on phase04/FullTextSearch.Test/QueryTest/QueryFormatter.cs
> +        [InlineData(new[] { "ali", "reza", "zahra", "mohammad" }, new[] { "+ali", "+reza", "+zahra", "+mohammad" })]
ایناهم چون خیلی طولانی و زیاد شدن شاید بد نباشه ClassData بزنید

2024-08-01 08:29 UTC, tahadavari commented on phase04/FullTextSearch.Test/QueryTest/QueryFormatter.cs
> +    public class QueryFormatterTest
اسم فایل اصلاح بشه

2024-08-01 08:29 UTC, tahadavari commented on phase04/FullTextSearch.Test/QueryTest/QueryFormatter.cs
> +        {
تستای این کلاس چرا AAA نیستند <؟

2024-08-02 12:12 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/DocumentTest/DocumentBuilderTest.cs
> +            _documentBuilder = new DocumentBuilder(_documentFormatter);
sovel

2024-08-02 12:12 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/DocumentTest/DocumentBuilderTest.cs
> +{
solve

2024-08-02 12:13 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/MapTest/InvertedIndexMapperTest.cs
> +            var mapper = new InvertedIndexMapper();
😲

2024-08-02 12:14 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/QueryTest/QueryFormatter.cs
> +        [InlineData(new[] { "+ali", "+mohammad" }, new[] { "+ali", "-reza", "zahra", "+mohammad" }, '+')]
solve

2024-08-02 12:26 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/QueryTest/QueryFormatter.cs
> +        [InlineData(new[] { "ali", "reza", "zahra", "mohammad" }, new[] { "+ali", "+reza", "+zahra", "+mohammad" })]
what is diffrence beetwen **ClassData**  and **MemberData** ?

2024-08-02 12:28 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/QueryTest/QueryFormatter.cs
> +        {
چون نیاز به arrange نیست

2024-08-02 12:31 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/QueryTest/QueryFormatter.cs
> +        {
نیازه؟

2024-08-03 12:12 UTC, AliSK81 approved these changes
خسته نباشید

2024-08-03 12:12 UTC, AliSK81 commented on phase04/FullTextSearch.Controller/DocumentController/Abstraction/IDocumentDirector.cs
> +    public void Construct(string name, string path, string text, IDocumentBuilder documentBuilder);
توی اینترفیس public نگذاریم
چون ذاتا هرچیزی داخل اینترفیس پابلیکه

2024-08-03 12:12 UTC, AliSK81 commented on phase04/FullTextSearch.Controller/DocumentController/Abstraction/IDocumentFormatter.cs
> +    public IEnumerable<string> RemoveStopWords();
remove public

2024-08-03 12:12 UTC, AliSK81 commented on phase04/FullTextSearch.Controller/DocumentController/DocumentBuilder.cs
> +        _documentFormatter = documentFormatter;
check for argument null exception

2024-08-03 12:12 UTC, AliSK81 commented on phase04/FullTextSearch.Controller/DocumentController/DocumentFormatter.cs
> +        throw new NotImplementedException();
اگه این تابع نیازی به پیاده سازی نداره، میتونیم بگیم طراحیمون خوب نبوده و شاید Interface segregationراه حل باشه

2024-08-03 12:12 UTC, AliSK81 commented on phase04/FullTextSearch.Controller/QueryController/QueryBuilder.cs
> +        var splittedText = _queryFormatter.Split(_queryFormatter.ToUpper(_query.Text), " "); // [^A-Z]+
کامنت توی کد خوب نیست

2024-08-03 12:12 UTC, AliSK81 commented on phase04/FullTextSearch.Test/ControllerTest/SearchControllerTest/MinusSearcherTest.cs
> +        document1.Words = new List<string> {"cat", "reza", "hello"};
var document1 = new Document
{
    Name = "Doc1",
    Path = "./ResourcesTest/Doc1",
    Text = "reza ali mohammad hello",
    Words = new List<string> { "cat", "reza", "hello" }
};

2024-08-03 12:12 UTC, AliSK81 commented on phase04/FullTextSearch.Test/ServiceTest/InitializeServiceTest/InitializeServiceTest.cs
> +        documents.Add(documentBuilders[2].GetDocument());
با for مینوشتیم اشکالی نداشت

2024-08-03 12:12 UTC, AliSK81 commented on phase04/FullTextSearch.Test/ServiceTest/SearchServiceTest/SearchServiceTest.cs
> +    public void Search_ShouldReturnResultForPassesQuery()
چی باعث میشه تست هامون بزرگ و long method بشن؟

2024-08-03 12:40 UTC, tahadavari approved these changes

2024-08-03 12:40 UTC, tahadavari commented on phase04/FullTextSearch.Test/ControllerTest/ResultControllerTest/ResultBuilderTest.cs
> +        Document document3 = new Document();
var document3 = new Document
        {
            Name = "Doc3",
            Path = "./ResourcesTest/Doc3",
            Text = "reza ali mohammad hello",
            Words = new List<string> {"cat", "ali", "hello"}
        };

2024-08-03 12:40 UTC, tahadavari commented on phase04/FullTextSearch.Test/ControllerTest/ResultControllerTest/ResultBuilderTest.cs
> +        Document document3 = new Document();
var document3 = new Document
        {
            Name = "Doc3",
            Path = "./ResourcesTest/Doc3",
            Text = "reza ali mohammad hello",
            Words = new List<string> {"cat", "ali", "hello"}
        };

2024-08-03 12:40 UTC, tahadavari commented on phase04/FullTextSearch.Test/ControllerTest/ResultControllerTest/ResultBuilderTest.cs
> +        Document document3 = new Document();
و بقیه جاها

2024-08-03 12:40 UTC, tahadavari commented on phase04/FullTextSearch.Test/ControllerTest/SearchControllerTest/MinusSearcherTest.cs
> +        document1.Words = new List<string> {"cat", "reza", "hello"};
عه علیم گذاشته بود

2024-08-03 13:14 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Controller/DocumentController/Abstraction/IDocumentDirector.cs
> +    public void Construct(string name, string path, string text, IDocumentBuilder documentBuilder);
solve

2024-08-03 13:14 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Controller/DocumentController/Abstraction/IDocumentFormatter.cs
> +    public IEnumerable<string> RemoveStopWords();
solve

2024-08-03 13:16 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Controller/DocumentController/DocumentFormatter.cs
> +        throw new NotImplementedException();
یه بار پاکش کرده بودیم اون اواسط فاز قبلی اصلا حواسم نبود بهش کامیتش کنم

2024-08-03 13:16 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Controller/QueryController/QueryBuilder.cs
> +        var splittedText = _queryFormatter.Split(_queryFormatter.ToUpper(_query.Text), " "); // [^A-Z]+
100%

2024-08-03 14:25 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/ControllerTest/SearchControllerTest/MinusSearcherTest.cs
> +        document1.Words = new List<string> {"cat", "reza", "hello"};
😲

2024-08-03 14:26 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/ControllerTest/ResultControllerTest/ResultBuilderTest.cs
> +        Document document3 = new Document();
solve

2024-08-03 14:26 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/ControllerTest/ResultControllerTest/ResultBuilderTest.cs
> +        Document document3 = new Document();
solve

2024-08-03 14:28 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/ServiceTest/SearchServiceTest/SearchServiceTest.cs
> +    public void Search_ShouldReturnResultForPassesQuery()
کد های تکراری و وارد کردن دیتا های زیاد برای تست
شاید کاری که بشه با یک دیکشنری کرد داریم با چندتا میکنیم
بازم باید حضوری بحث کرد:)

2024-08-03 15:37 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/ServiceTest/InitializeServiceTest/InitializeServiceTest.cs
> +        documents.Add(documentBuilders[2].GetDocument());
solve

2024-08-03 15:44 UTC, AmirRezaZahedi commented on phase04/FullTextSearch.Test/ServiceTest/SearchServiceTest/SearchServiceTest.cs
> +    public void Search_ShouldReturnResultForPassesQuery()
ممکنه تابع ها چند کاره باشن ولی مال ما نبود تا حداکثرممکن

2024-08-08 07:40 UTC, merged